/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-12-2014
 * 
 * XDoclet definition:
 * @struts.form name="floorForm"
 */
public class FloorForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** floorName property */
	private String floorName;

	/** floorId property */
	private String floorId;

	/** floorDesc property */
	private String floorDesc;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the floorName.
	 * @return String
	 */
	public String getFloorName() {
		return floorName;
	}

	/** 
	 * Set the floorName.
	 * @param floorName The floorName to set
	 */
	public void setFloorName(String floorName) {
		this.floorName = floorName;
	}

	/** 
	 * Returns the floorId.
	 * @return String
	 */
	public String getFloorId() {
		return floorId;
	}

	/** 
	 * Set the floorId.
	 * @param floorId The floorId to set
	 */
	public void setFloorId(String floorId) {
		this.floorId = floorId;
	}

	/** 
	 * Returns the floorDesc.
	 * @return String
	 */
	public String getFloorDesc() {
		return floorDesc;
	}

	/** 
	 * Set the floorDesc.
	 * @param floorDesc The floorDesc to set
	 */
	public void setFloorDesc(String floorDesc) {
		this.floorDesc = floorDesc;
	}
}