/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vcs.service.FloorService;
import com.vcs.struts.form.FloorForm;


public class FloorAction extends Action {
	
	private FloorService floorService;
	
	public void setFloorService(FloorService floorService) {
		this.floorService = floorService;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FloorForm floorForm = (FloorForm) form;
		
		//FloorService floorService=ServiceFactory.getFloorService();
		floorService.serviceMethod();
		
		return mapping.findForward("success");
	}
}